### PR TITLE
Use strong types for key and bare item integer, decimal, token, and string

### LINKED ISSUE #98: Validation of Items on local contruction
sfv implements parsing validation, per the rules in RFC 8941. For example, Tokens are checked for valid character usage in https://github.com/undef1nd/sfv/blob/master/src/parser.rs#L290

However, I might have missed it but there doesn't appear to be an equivalent validation in the library when constructing such items. It seems like it would be helpful to support this, without having to resort to construction, serialization, and parsing. 

For instance, the backing type to Token is String. And the docs suggest that I could create an Item of type Token by using

```
let token = BareItem::Token("12345");
```

This would strictly be an invalid token according to https://www.rfc-editor.org/rfc/rfc8941.html#section-3.3.4-7 - `the first character is required to be either ALPHA or "*"`

Of course, we could require that implementations sanitize their own values before passing into sfv. But then, sfv already implements the checks, just they aren't exposed in an easy way. It would be great to expose them for reuse.

The use case here is applications that pass through values from other things. If the receiving endpoint fails to parse that it will cause interop issues. It would be muc better if the sender had an opportunity to validate things before sending them, so that it might take mitigating action. There are probably still cases where a sender doesn't care, so perhaps checked and unchecked variants are required.

### PR DESCRIPTION
**Pull request by apasel422**
This is an updated version of #102 that takes the following approach:

1. `BareItem` and `RefBareItem` contain only fully validated types.
2. Dictionary and parameter keys are likewise fully validated.
3. A number of helpers based on `Into` and `TryInto` simplify creation of these types from unvalidated inputs, including at compile-time using `const fn`.
4. Parsing produces these fully validated types.
5. Serialization accepts only these fully validated types, making serialization in general infallible (the only real errors being empty list and empty dictionary) and presumably improving performance in the likely common case that components are fully validated at compile time.
6. `rust_decimal::Decimal` is replaced with an `sfv::Decimal` type that simply wraps the new `Integer` type, as an [SFV decimal](https://httpwg.org/specs/rfc8941.html#decimal) is 12 integral digits and 3 fractional digits, while an [SFV integer](https://httpwg.org/specs/rfc8941.html#integer) is 15 decimal digits.
7. The new `sfv::{Key, String, Token}` types are the owned equivalents of the new `sfv::{KeyRef, StringRef, TokenRef}` types, analogous to `Vec<T>` vs `[T]`.

As part of #119, we will likewise introduce an `sfv::Date` type that wraps `Integer`.

Fixes #98

### CODE REVIEW

**Comment by apasel422** [comment]
CC @valenting

File: src/ref_serializer.rs [hunk 1]
```diff
@@ -40,32 +41,29 @@ pub struct RefParameterSerializer<'a> {
...
-/// use sfv::{RefBareItem, RefListSerializer};
+/// use sfv::{key_ref, string_ref, token_ref, RefListSerializer};
 ///
 /// let mut serialized_item = String::new();
 /// let serializer = RefListSerializer::new(&mut serialized_item);
 /// serializer
 ///     .bare_item(11)
-///     .unwrap()
-///     .parameter("foo", true)
+///     .parameter(key_ref("foo"), true)
```
Comment (valenting) [inline src/ref_serializer.rs:58]: Let's use KeyRef::from_str here. We don't want people to just use the panicking versions immediately.
We can give examples with the panicking ones too, as long as they're not the first ones 🙂

**Review by valenting — CHANGES_REQUESTED** [review]
Looks great, generally.
I'd like some minor documentation changes, where we use the fallible `from_str` functions to create keys, etc.
Otherwise devs will just copy-paste the first example and end up with a panic when the string is provided by the user.

**Review by valenting — APPROVED** [review]
Looks great, thank you!
